# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
