# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_customer_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
